spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smtpz_lab
    username: postgres
    password: postgres23
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

eureka:
  client:
    serviceUrl:
      defaultZone: http://smtpz.lab:8761/eureka
  instance:
    preferIpAddress: true