spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/smtpz_lab
    username: root
    password: root
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

message: Hello, world
